### ISSUE TITLE
常用CSS查看表

### ISSUE THREAD

**Issue by shaobeichen** [shaobeichen/blog#15]
![banner](https://user-images.githubusercontent.com/18715564/42683964-63d6bd4e-86c1-11e8-8510-3ddcb11023fa.png#width-full)

> 平时要使用的常用CSS比较多，比如多行省略，单行省略，诸如此类，每次都一个一个查麻烦，直接保存我这个网页，打开之后，Ctrl+F查找就行了，美滋滋。

### 单行文本的溢出显示省略号

``` css
p {
   overflow: hidden;
   text-overflow: ellipsis;
   white-space: nowrap;
}
```

### 多行文本的溢出显示省略号

``` css
p {
   overflow : hidden;
   text-overflow: ellipsis;
   display: -webkit-box;
   -webkit-line-clamp: 2;
   -webkit-box-orient: vertical;
}
```

### 单选框美化样式

``` css
 input[type='radio'] {
    background: url("../images/enterfor/enterfor_03.png") no-repeat center/cover;
    -webkit-appearance: none;
    width: 23px;
    height: 23px;
    margin-left: -30px;
    border-radius: 0;
    border: none !important;
}

 input[type='radio']:checked {
    background: url("../images/enterfor/enterfor_02.png") no-repeat center/cover;
}
```

### background-size 失效
这样写的话 background-size 没效果
``` css
{
background-size:contain;
background:url(xxx);
}
```
把两个交换下顺序，即换成下面这样就生效了
``` css
{
background:url(xxx);
background-size:contain;
}
 ```
